#!/usr/bin/env bash
#
# generate-docs.sh — regenerate the API reference Markdown under docs/reference/
# from godoc comments in source.
#
# See specs/project/documentation.spec.md ("scripts/generate-docs.sh"). The
# script runs the godoc-to-Markdown tool (gomarkdoc) over every buildable Go
# package in the module and writes one Markdown file per package into
# docs/reference/. The output is committed and consumed by Zensical as ordinary
# source files; it must not be edited by hand.
#
# Today only the root `blkit` package exists. As decisions/processes/etc. land,
# they are documented automatically — the package list is discovered with
# `go list ./...`, so nothing here needs to change.
#
# Exits non-zero with a structured message if generation fails.

set -euo pipefail

readonly MODULE_PATH="github.com/friendly-business-machines/blkit"
readonly GOMARKDOC_VERSION="v1.1.0"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
readonly REPO_ROOT
readonly REFERENCE_DIR="${REPO_ROOT}/docs/reference"
readonly GENERATED_BANNER="<!-- Generated by scripts/generate-docs.sh — DO NOT EDIT. -->"

fail() {
  echo "generate-docs: ERROR: $*" >&2
  exit 1
}

cd "$REPO_ROOT"

command -v go >/dev/null 2>&1 || fail "go is not installed or not on PATH"

# Ensure gomarkdoc is available; install the pinned version if it is missing.
if ! command -v gomarkdoc >/dev/null 2>&1; then
  echo "generate-docs: installing gomarkdoc ${GOMARKDOC_VERSION}"
  go install "github.com/princjef/gomarkdoc/cmd/gomarkdoc@${GOMARKDOC_VERSION}" \
    || fail "failed to install gomarkdoc ${GOMARKDOC_VERSION}"
  PATH="${PATH}:$(go env GOPATH)/bin"
fi

# Discover every buildable package in the module.
packages=()
while IFS= read -r line; do
  packages+=("$line")
done < <(go list ./... 2>/dev/null) || fail "go list failed — module does not build"

[ "${#packages[@]}" -gt 0 ] || fail "no Go packages found to document"

mkdir -p "$REFERENCE_DIR"

for pkg in "${packages[@]}"; do
  # Derive a stable, flat file name from the import path: the root package
  # becomes blkit.md, sub-packages become e.g. decisions.md, data.md.
  rel="${pkg#"$MODULE_PATH"}"
  rel="${rel#/}"
  name="${rel:-blkit}"
  name="${name//\//-}"
  out="${REFERENCE_DIR}/${name}.md"

  echo "generate-docs: ${pkg} -> docs/reference/${name}.md"
  gomarkdoc --output "$out" "$pkg" || fail "gomarkdoc failed for ${pkg}"

  # Prepend the generated-file banner.
  tmp="$(mktemp)"
  { printf '%s\n\n' "$GENERATED_BANNER"; cat "$out"; } >"$tmp"
  mv "$tmp" "$out"
  chmod 0644 "$out"
done

echo "generate-docs: wrote reference Markdown for ${#packages[@]} package(s) to docs/reference/"
