#!/usr/bin/env bash
#
# generate-llms.sh — regenerate the LLM discovery files docs/llms.txt and
# docs/llms-full.txt from zensical.toml and the documentation pages under docs/.
#
# See specs/project/documentation.spec.md ("LLM Discovery Files"). llms.txt is a
# concise, curated index of the site (per the https://llmstxt.org/ convention);
# llms-full.txt concatenates the full text of every page — including the
# generated API reference — so a model can ingest everything in one fetch. Both
# files are committed and copied verbatim into the site output by Zensical.
#
# The nav in zensical.toml is the single source of truth: links and ordering are
# derived from it so the discovery files never drift from the published pages.
# Because llms-full.txt embeds the generated reference under docs/reference/,
# run scripts/generate-docs.sh *before* this script.
#
# Parsing the (nested) TOML nav reliably needs a real parser, so the logic is
# Python using the stdlib `tomllib` module (Python 3.11+). No third-party
# packages are installed. Exits non-zero with a structured message on failure.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export REPO_ROOT

fail() {
  echo "generate-llms: ERROR: $*" >&2
  exit 1
}

command -v python3 >/dev/null 2>&1 || fail "python3 is not installed or not on PATH"
python3 -c 'import tomllib' >/dev/null 2>&1 \
  || fail "python3 with the tomllib module (Python 3.11+) is required"

python3 - <<'PY'
import os
import re
import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(os.environ["REPO_ROOT"])
BANNER = "<!-- Generated by scripts/generate-llms.sh — DO NOT EDIT. -->"


def fail(msg):
    sys.stderr.write(f"generate-llms: ERROR: {msg}\n")
    sys.exit(1)


config_path = REPO_ROOT / "zensical.toml"
try:
    with config_path.open("rb") as fh:
        config = tomllib.load(fh)
except OSError as exc:
    fail(f"could not read {config_path}: {exc}")
except tomllib.TOMLDecodeError as exc:
    fail(f"could not parse {config_path}: {exc}")

project = config.get("project", {})
site_name = project.get("site_name") or fail("zensical.toml: project.site_name is required")
site_desc = project.get("site_description", "")
site_url = (project.get("site_url") or fail("zensical.toml: project.site_url is required")).rstrip("/") + "/"
docs_dir = REPO_ROOT / project.get("docs_dir", "docs")
nav = project.get("nav") or fail("zensical.toml: project.nav is required")


def page_url(md_path):
    """Map a docs-relative Markdown path to its directory-URL form."""
    stem = md_path[:-3] if md_path.endswith(".md") else md_path
    if stem == "index":
        return site_url
    if stem.endswith("/index"):
        stem = stem[: -len("/index")]
    return f"{site_url}{stem}/"


def read_page(md_path):
    path = docs_dir / md_path
    if not path.is_file():
        fail(f"nav references a page that does not exist: {path}")
    return path.read_text(encoding="utf-8")


def first_heading(text, fallback):
    for line in text.splitlines():
        match = re.match(r"#\s+(.*)", line.strip())
        if match:
            return match.group(1).strip()
    return fallback


def first_blockquote(text):
    """Return the page's opening blockquote summary, unwrapped to one line."""
    collected = []
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith(">"):
            collected.append(stripped.lstrip(">").strip())
        elif collected:
            break  # blockquote ended
        elif not stripped or stripped.startswith("#"):
            continue  # skip leading blanks and the page H1
        else:
            break  # first real content is not a blockquote
    return " ".join(part for part in collected if part).strip()


# Walk the nav once, building both the grouped index (llms.txt) and the ordered
# page list (llms-full.txt).
doc_pages = []   # top-level single pages -> (title, url, desc)
list_groups = []  # (label, [(title, url, desc), ...])
ordered = []      # (url, md_path) in nav order, for the full concatenation


def add_child(label, child):
    if isinstance(child, str):
        text = read_page(child)
        ordered.append((page_url(child), child))
        return (first_heading(text, label), page_url(child), first_blockquote(text))
    if isinstance(child, dict):
        (clabel, cpath), = child.items()
        text = read_page(cpath)
        ordered.append((page_url(cpath), cpath))
        return (clabel, page_url(cpath), first_blockquote(text))
    fail(f"unsupported nav child entry: {child!r}")


for entry in nav:
    (label, value), = entry.items()
    if isinstance(value, str):
        text = read_page(value)
        ordered.append((page_url(value), value))
        doc_pages.append((label, page_url(value), first_blockquote(text)))
    elif isinstance(value, list):
        list_groups.append((label, [add_child(label, child) for child in value]))
    else:
        fail(f"unsupported nav entry: {entry!r}")


def render_links(items):
    lines = []
    for title, url, desc in items:
        line = f"- [{title}]({url})"
        if desc:
            line += f": {desc}"
        lines.append(line)
    return "\n".join(lines)


# --- llms.txt ---------------------------------------------------------------
sections = [f"{BANNER}\n# {site_name}", f"> {site_desc}"]
if doc_pages:
    sections.append("## Documentation\n" + render_links(doc_pages))
for label, items in list_groups:
    sections.append(f"## {label}\n" + render_links(items))
llms_txt = "\n\n".join(sections) + "\n"

# --- llms-full.txt ----------------------------------------------------------
header = "\n\n".join([
    f"{BANNER}\n# {site_name}",
    f"> {site_desc}",
    "This file contains the full text of the blkit documentation, "
    "concatenated for large-language-model consumption.",
])
page_blocks = [
    f"<!-- Source: {url} -->\n\n{read_page(md_path).rstrip()}"
    for url, md_path in ordered
]
llms_full = header + "\n\n---\n\n" + "\n\n---\n\n".join(page_blocks) + "\n"

(docs_dir / "llms.txt").write_text(llms_txt, encoding="utf-8")
(docs_dir / "llms-full.txt").write_text(llms_full, encoding="utf-8")
print(f"generate-llms: wrote docs/llms.txt and docs/llms-full.txt "
      f"({len(ordered)} pages)")
PY
