#!/usr/bin/env bash
#
# generate-docs.sh — regenerate the API reference Markdown under docs/reference/
# from godoc comments in source.
#
# See specs/project/documentation.spec.md ("scripts/generate-docs.sh"). The
# script runs the godoc-to-Markdown tool (gomarkdoc) over every buildable Go
# package in the workspace and writes one Markdown file per package into
# docs/reference/. The output is committed and consumed by Zensical as ordinary
# source files; it must not be edited by hand.
#
# The `core` package (imported as `bl`) is documented as blkit.md. Each
# state-store backend under stores/<name>/ is its own module and is documented
# as stores-<name>.md. As the messagegateway/worker/restserver packages land,
# they are documented automatically too — the package list is discovered from
# `go list`, so nothing here needs to change.
#
# Exits non-zero with a structured message if generation fails.

set -euo pipefail

readonly MODULE_PATH="github.com/friendly-business-machines/blkit"
readonly GOMARKDOC_VERSION="v1.1.0"

# Pin the source-link target. gomarkdoc otherwise auto-detects the git ref for
# its `blob/<ref>/file#Lnn` links, which is environment-dependent: a local clone
# resolves the branch name (main), but CI's detached, shallow actions/checkout
# falls back to the commit SHA. That made every link line differ between local
# and CI, so the committed reference always looked stale. Override the three
# repository fields so links are identical everywhere.
readonly REPO_URL="https://${MODULE_PATH}"
readonly REPO_BRANCH="main"
readonly REPO_DOC_PATH="/"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
readonly REPO_ROOT
readonly REFERENCE_DIR="${REPO_ROOT}/docs/reference"
readonly GENERATED_BANNER="<!-- Generated by scripts/generate-docs.sh — DO NOT EDIT. -->"

fail() {
  echo "generate-docs: ERROR: $*" >&2
  exit 1
}

cd "$REPO_ROOT"

command -v go >/dev/null 2>&1 || fail "go is not installed or not on PATH"

# Ensure gomarkdoc is available; install the pinned version if it is missing.
if ! command -v gomarkdoc >/dev/null 2>&1; then
  echo "generate-docs: installing gomarkdoc ${GOMARKDOC_VERSION}"
  go install "github.com/princjef/gomarkdoc/cmd/gomarkdoc@${GOMARKDOC_VERSION}" \
    || fail "failed to install gomarkdoc ${GOMARKDOC_VERSION}"
  PATH="${PATH}:$(go env GOPATH)/bin"
fi

mkdir -p "$REFERENCE_DIR"

# document_pkg IMPORT_PATH OUTPUT_NAME WORKDIR REPO_PATH [GOWORK]
#
# Generate docs/reference/OUTPUT_NAME.md for one package. gomarkdoc is run from
# WORKDIR so it resolves the package in the intended module context, and
# REPO_PATH is the package's path within the repository (mapped to the module
# root) so the source-link URLs point at the right subdirectory. When GOWORK is
# given (e.g. "off") it is exported for the invocation — used to document the
# store backends in single-module mode; see the store loop below.
document_pkg() {
  local import_path="$1" name="$2" workdir="$3" repo_path="$4" gowork="${5:-}"
  local out="${REFERENCE_DIR}/${name}.md"

  echo "generate-docs: ${import_path} -> docs/reference/${name}.md"
  (
    cd "$workdir"
    [ -n "$gowork" ] && export GOWORK="$gowork"
    gomarkdoc \
      --repository.url "$REPO_URL" \
      --repository.default-branch "$REPO_BRANCH" \
      --repository.path "$repo_path" \
      --output "$out" "$import_path"
  ) || fail "gomarkdoc failed for ${import_path}"

  # Un-escape parentheses. gomarkdoc targets GitHub-flavored Markdown and
  # defensively backslash-escapes parentheses in headings and link text (e.g.
  # `func \(BlBoolean\) IsNull`). GitHub renders `\(` as a bare `(`, but
  # Zensical's Markdown engine leaves the backslash in heading plain text, so
  # the literal `\(` `\)` leak into the rendered page. Parentheses carry no
  # Markdown meaning in the positions they appear here (real link destinations
  # use the un-escaped `](<#anchor>)` form), so stripping the escape is safe.
  # Scoped to parentheses only: brackets, angle brackets and backticks are
  # load-bearing inside link text and code spans and are left untouched.
  sed -i 's/\\(/(/g; s/\\)/)/g' "$out"

  # Prepend the generated-file banner.
  local tmp
  tmp="$(mktemp)"
  { printf '%s\n\n' "$GENERATED_BANNER"; cat "$out"; } >"$tmp"
  mv "$tmp" "$out"
  chmod 0644 "$out"
}

count=0

# Core module. `go list ./...` from the repo root finds its packages directly.
core_pkgs="$(go list ./... 2>/dev/null)" || fail "go list failed — module does not build"
[ -n "$core_pkgs" ] || fail "no Go packages found to document"
while IFS= read -r pkg; do
  [ -n "$pkg" ] || continue
  # Derive a stable, flat file name from the import path: the core package
  # becomes blkit.md (it is the project's primary reference page and the site
  # nav links to reference/blkit.md), sub-packages become e.g. messagegateway.md.
  rel="${pkg#"$MODULE_PATH"}"
  rel="${rel#/}"
  name="${rel:-blkit}"
  name="${name//\//-}"
  [ "$name" = "core" ] && name="blkit"
  document_pkg "$pkg" "$name" "$REPO_ROOT" "$REPO_DOC_PATH"
  count=$((count + 1))
done <<< "$core_pkgs"

# Pluggable backend families. Each stores/<name>/ and brokers/<name>/ is its OWN
# Go module, and both go.work and go.work.sum are git-ignored — so they are
# absent from a fresh CI checkout. Discovering the backends through the workspace
# (`go list ./stores/<name>/...` from the root) therefore works locally but fails
# in CI with "directory prefix ... does not contain main module". Instead,
# document each backend in SINGLE-MODULE mode: run go/gomarkdoc with GOWORK=off
# from inside the module directory, so resolution depends only on that module's
# own committed go.mod/go.sum. The repo path is set to /<family>/<name> so the
# source-link URLs still point at the module's subdirectory in the repository.
#
# Each backend module becomes reference/<family>-<name>.md (e.g. a stores module
# becomes stores-postgres.md, a brokers module becomes brokers-redis.md).
document_module_family() {
  local family="$1"   # e.g. stores or brokers
  [ -d "${REPO_ROOT}/${family}" ] || return 0
  local dir mod mod_pkgs pkg rel name
  for dir in "${REPO_ROOT}/${family}"/*/; do
    [ -f "${dir}go.mod" ] || continue
    mod="$(basename "$dir")"
    mod_pkgs="$(cd "$dir" && GOWORK=off go list ./...)" \
      || fail "go list failed for ${family} module ${mod} — module does not build"
    while IFS= read -r pkg; do
      [ -n "$pkg" ] || continue
      rel="${pkg#"$MODULE_PATH"/}"   # e.g. stores/postgres or brokers/redis
      name="${rel//\//-}"            # stores-postgres or brokers-redis
      document_pkg "$pkg" "$name" "$dir" "/${rel}" "off"
      count=$((count + 1))
    done <<< "$mod_pkgs"
  done
}

document_module_family stores
document_module_family brokers

echo "generate-docs: wrote reference Markdown for ${count} package(s) to docs/reference/"
